### ISSUE TITLE
buildBreakpointClassNames: remove grid opinions

### ISSUE THREAD

**Issue by andrewrubin** [wethegit/component-library#100]
The `buildBreakpointClassnames` helper is AWESOME, but it needs to be less opinionated. Currently it only generates classes for medium-up, but there's not a great reason to do that — as "medium-up" is a grid-specific convention that we use.

## Goal
I would like to be able to add classes for `small-only` as an example. `<ChildSpacing>`, for example (still to-do), will often need spacing for the small breakpoint only (when columns stack vertically).

## Suggestion:
- add more breakpoint options to this helper — `sm`, `sm-only `, etc.

### Caveat
This will break the grid layout classname generation, so we'll need to update that a bit

**Comment by andrewrubin** [comment]
Resurrecting this, per the conversations in #181 

@marlonmarcello to address your earlier question:

> _Is there an example where our mobile-first approach wouldn't solve this? For the example of the childSpacing, you can start with margin-bottom-2 on small and then apply margin-bottom-medium-0 to overwrite it._

The issue that I'd like to address is that the classname generator _doesn't_ actually create a "medium-" prefixed class. I think maybe this function needs an option like `baseBreakpoint` or `defaultBreakpoint` or `startingBreakpoint`, which decides what breakpoint is the "base".

For example, on our grid system, we could do (pseudo-code):
```
buildBreakpointClassnames(existing args, startingBreakpoint: "md")
```
Which would generate `column--6`, `column-lg--5`, `column-xl-4` and so on, _starting_ at medium as the base.


And for something like the `<Flex>` component, we could do:
```
buildBreakpointClassnames(existing args, startingBreakpoint: "sm")
```
Which would generate something like `justify-center`, `justify-md-start`, `justify-lg-end`, and so on, starting with small as the base.

Let me know your thoughts, thanks!

**Comment by andrewrubin** [comment]
Another option for this, is to just add a check to see if the user passed in a value for `sm`, and adjust things accordingly.

**Comment by marlonmarcello** [comment]
I like that and I think that's a great idea @andrewrubin 
Let's go ahead and implement it!
