### ISSUE TITLE
[DOCS] animation: missing instructions to add styles to global stylesheet

### ISSUE THREAD

**Issue by marlonmarcello** [wethegit/component-library#151]
# Description

The `animation` styles require the user to add the main stylesheet to their global styles but we are not instructing them to do so.

**Comment by marlonmarcello** [comment]
Ohh. I feel like I may have wrote this wrong. I can't quite remember now. Maybe it's an issue inside corgi?

**Comment by andrewrubin** [comment]
I don't think it is, but we'll keep it open in case you remember. our Corgi templates removed all global stylsheets, and installing the component library overwrites that anyway

**Comment by marlonmarcello** [comment]
I did a fresh install of a project and everything is fine. I am not sure what spurred this but will close for now.
