### ISSUE TITLE
[COMP] Add `0` to spacing range

### ISSUE THREAD

**Issue by marlonmarcello** [wethegit/component-library#157]
We are missing the `0` in the range so we can remove the spacing in certain breakpionts. The styles already account for that, it's just a matter of using the correct range for the types.

https://github.com/wethegit/component-library/blob/99072899ba94331e19bbeb743b3f0ba342f171cd/packages/wethegit-components/src/utilities/spacing/spacing.ts#L8

**Comment by andrewrubin** [comment]
Closing as fixed via #170 

Added in release v3.0.5
