### ISSUE TITLE
[COMP] Update `<Modal/>` to use `dialog` with `showModal`

### ISSUE THREAD

**Issue by marlonmarcello** [wethegit/component-library#163]
The `dialog` element is available in all browsers including Safari since `15` and the `showModal` method traps focus automatically.

Note: Might need some more investigation and testing.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/showModal

**Comment by andrewrubin** [comment]
This is probably better as an issue on the react-modal package than on the component library. Any specific reason you wanted it here though, @marlonmarcello?

**Comment by marlonmarcello** [comment]
You are right @andrewrubin this should be in that package's repo.

**Comment by marlonmarcello** [comment]
That's done: https://github.com/wethegit/react-modal/issues/114
